server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /schedule-service
spring:
  application:
    name: schedule-service
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432}/schedule_service
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432}/schedule_service
    schemas: public
    user: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}